### ISSUE TITLE
Unable to search for Unicode titles

### ISSUE THREAD

**Issue by satelliteseeker** [XorTroll/CDNTool#1]
Version: v0.1
Description: No results are returned when the search keyword contains Unicode (for example, Japanese) characters.
![capture](https://user-images.githubusercontent.com/15308471/36943566-7f1e2760-1f40-11e8-88f3-ddb02882a478.PNG)

The title name displayed in the prompt window is also incorrect with all Unicode character missing.
 - Title name: II
 - Region: Japan (JPN)
 - Title ID: 00040000000f8e00
 - Code name: CTR-N-TDQJ
 - Encrypted Key: [REDACTED]
 - Total size (MB): 6.1 MB
(The correct title: ファイナルファンタジーII)

**Comment by XorTroll** [comment]
I've remade the entire program for beta 2, and looks quite better in lots of things.
I'm glad to say that JS and HTML code support unicode search!
![scren](https://user-images.githubusercontent.com/33005497/38328138-5e0b4f3a-384a-11e8-96a6-2c5760175c0f.PNG)
